apiVersion: v1
entries:
  api-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.392790457Z"
    description: A Helm chart for Kubernetes
    digest: 354a53074e5aa06fbcf2b28ee0984b921d587d344ed8258cc18be017a0c16bf2
    name: api-gateway
    type: application
    urls:
    - spinnaker/api-gateway-0.1.0+312140c.tgz
    version: 0.1.0+312140c
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.394193777Z"
    description: A Helm chart for Kubernetes
    digest: 5a1d328adee3dc1e1a3c3b7616e95fdf070c24f9c19838ebb27c5b1d9d16851e
    name: api-gateway
    type: application
    urls:
    - spinnaker/api-gateway-0.1.0+4862555.tgz
    version: 0.1.0+4862555
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.394874986Z"
    description: A Helm chart for Kubernetes
    digest: 53815586f2a833c871aca08010292cab636eb706ec84b3d53790d387a256cae5
    name: api-gateway
    type: application
    urls:
    - spinnaker/api-gateway-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
  authentication-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.401389578Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: a6945c0bb6708fffa8b06faf191531162b6c93490889094cfefc6c9040d8c37a
    name: authentication-service
    type: application
    urls:
    - spinnaker/authentication-service-0.1.0+312140c.tgz
    version: 0.1.0+312140c
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.408526978Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: 1c7dfe1145eba07ebef95ef7f6303b6552c3fb3cebd0f5682fcb8ac56f8a7909
    name: authentication-service
    type: application
    urls:
    - spinnaker/authentication-service-0.1.0+4862555.tgz
    version: 0.1.0+4862555
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.416637392Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: 147a20946ec75289840d3b55e1aea334726b683aa1818cc0758c6acd58b4d1f4
    name: authentication-service
    type: application
    urls:
    - spinnaker/authentication-service-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
  car-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.423089883Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: 7aae666e0b853288623e8b1bb595cb36220aacbb0fdd95edb4cba5dca3ffaf77
    name: car-service
    type: application
    urls:
    - spinnaker/car-service-0.1.0+312140c.tgz
    version: 0.1.0+312140c
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.430303484Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: 901c8a7205dd53be6a736982430f617026ab2a5213548124f5ab691502b1b7e9
    name: car-service
    type: application
    urls:
    - spinnaker/car-service-0.1.0+4862555.tgz
    version: 0.1.0+4862555
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.436797875Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: ba7cc2f6659ee416256cd2d70fd1e6155ef41643086870386a63952659856c16
    name: car-service
    type: application
    urls:
    - spinnaker/car-service-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
  configuration-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.437255682Z"
    description: A Helm chart for Kubernetes
    digest: 48b3bceba7b634a200bfba6cdc1d9d4cbab9bb91d486e903136bfe865ac10329
    name: configuration-service
    type: application
    urls:
    - spinnaker/configuration-service-0.1.0+312140c.tgz
    version: 0.1.0+312140c
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.437656988Z"
    description: A Helm chart for Kubernetes
    digest: 9c3d6375040b61264d1d1732e8c22acc1dde76149a0825f387d622c74323e00b
    name: configuration-service
    type: application
    urls:
    - spinnaker/configuration-service-0.1.0+4862555.tgz
    version: 0.1.0+4862555
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.438329797Z"
    description: A Helm chart for Kubernetes
    digest: fb24ed65380d9f2a71c93f29b53c1770619f65726135aec32f80e486dec150fe
    name: configuration-service
    type: application
    urls:
    - spinnaker/configuration-service-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
  currency-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.445161393Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: e188758abb7e81edebfea78b8871c7cd692a34c766a5ce1ba737f20a50b94099
    name: currency-service
    type: application
    urls:
    - spinnaker/currency-service-0.1.0+312140c.tgz
    version: 0.1.0+312140c
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.4527661Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: c50427697399154aae7a9321cf6279d95d920848befebfa50936ada2848d9883
    name: currency-service
    type: application
    urls:
    - spinnaker/currency-service-0.1.0+4862555.tgz
    version: 0.1.0+4862555
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.45919499Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: cf74b1ea3ee2160e8aa10a140435591628c08411752a3b8d52821be350c0923b
    name: currency-service
    type: application
    urls:
    - spinnaker/currency-service-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
  discovery-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.460558509Z"
    description: A Helm chart for Kubernetes
    digest: 31191025e7d4432e48a0839c9d0fb84fe4f0b0741639fc1ec93e40aff18d48e8
    name: discovery-service
    type: application
    urls:
    - spinnaker/discovery-service-0.1.0+312140c.tgz
    version: 0.1.0+312140c
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.461010216Z"
    description: A Helm chart for Kubernetes
    digest: 3948c3fd8066926edf56304b46b1cda687740565c1038d13af2ea3e983d9bdb3
    name: discovery-service
    type: application
    urls:
    - spinnaker/discovery-service-0.1.0+4862555.tgz
    version: 0.1.0+4862555
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.461456822Z"
    description: A Helm chart for Kubernetes
    digest: 34e72db7b2b9b2cef76f101d278b73473fa0b0b6967603258890c0d36dd83d7b
    name: discovery-service
    type: application
    urls:
    - spinnaker/discovery-service-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
  frontend:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.461827527Z"
    description: The frontend for car-rental application
    digest: 602210e6cd70f2ccd843b52a075056598608ef938f8a78f1444aa12fa1939bba
    name: frontend
    type: application
    urls:
    - spinnaker/frontend-0.0.1+312140c.tgz
    version: 0.0.1+312140c
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.462156332Z"
    description: The frontend for car-rental application
    digest: 984d6bf7318449d746916f69693ea980788aa2a253e5977211ca4911a692db86
    name: frontend
    type: application
    urls:
    - spinnaker/frontend-0.0.1+4862555.tgz
    version: 0.0.1+4862555
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.462480536Z"
    description: The frontend for car-rental application
    digest: dfbcacaf6c87fdd33ff04f0c7646bea0d309066cf594f92bb2cb7fc1dece1ab2
    name: frontend
    type: application
    urls:
    - spinnaker/frontend-0.0.1+ea86865.tgz
    version: 0.0.1+ea86865
  location-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.46983514Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: 541eb52aa6d57e4381f2eac39c174d9237dcb79002fa5bb688f4b93997a123c8
    name: location-service
    type: application
    urls:
    - spinnaker/location-service-0.1.0+312140c.tgz
    version: 0.1.0+312140c
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.477515348Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: b9fc0ce0d090ac7c3b1d9e21cea79c1af823fee4e97849eecd40b06f015b3366
    name: location-service
    type: application
    urls:
    - spinnaker/location-service-0.1.0+4862555.tgz
    version: 0.1.0+4862555
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.483868037Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: a44c3605a6f93219926873aa6d1d823853c8da0cd56b572fff54180086e0dc3f
    name: location-service
    type: application
    urls:
    - spinnaker/location-service-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
  opening-hours-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.492042652Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: ebbeff30faa0abcc96fbc4eb8ff6390de45fa2c01d646156378da0ffe672eac1
    name: opening-hours-service
    type: application
    urls:
    - spinnaker/opening-hours-service-0.1.0+312140c.tgz
    version: 0.1.0+312140c
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.498499043Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: c0cddc721c918b4e53968e2181cfaf590830d9f848b88167e472a6d0626decee
    name: opening-hours-service
    type: application
    urls:
    - spinnaker/opening-hours-service-0.1.0+4862555.tgz
    version: 0.1.0+4862555
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.506367853Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: 177e7ebff92bc635d31bc42c99cd9c9d7b0a130299684c0d95214bb2e411ac7a
    name: opening-hours-service
    type: application
    urls:
    - spinnaker/opening-hours-service-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
  order-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.512729543Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: f05c67ce6806c81e0c8f50f46b7dd70a94d3970ab92bb281e13190b25feeb5d7
    name: order-service
    type: application
    urls:
    - spinnaker/order-service-0.1.0+312140c.tgz
    version: 0.1.0+312140c
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.520103147Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: 4ffd8f28e43fa8fa8bb8b9d7e8c503abbd15c558d808f84ddbe12f8d33ba14aa
    name: order-service
    type: application
    urls:
    - spinnaker/order-service-0.1.0+4862555.tgz
    version: 0.1.0+4862555
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-20T19:34:49.527199846Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: 0dc9cd08bf519834c72829521df10e2dc3c3f0968be712a921843ce1b417c4b3
    name: order-service
    type: application
    urls:
    - spinnaker/order-service-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
generated: "2023-03-20T19:34:49.390442824Z"
