apiVersion: v1
entries:
  api-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-19T15:35:34.359243567Z"
    description: A Helm chart for Kubernetes
    digest: 53815586f2a833c871aca08010292cab636eb706ec84b3d53790d387a256cae5
    name: api-gateway
    type: application
    urls:
    - spinnaker/api-gateway-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
  authentication-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-19T15:35:34.370734266Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: 147a20946ec75289840d3b55e1aea334726b683aa1818cc0758c6acd58b4d1f4
    name: authentication-service
    type: application
    urls:
    - spinnaker/authentication-service-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
  car-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-19T15:35:34.378123694Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: ba7cc2f6659ee416256cd2d70fd1e6155ef41643086870386a63952659856c16
    name: car-service
    type: application
    urls:
    - spinnaker/car-service-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
  configuration-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-19T15:35:34.378538001Z"
    description: A Helm chart for Kubernetes
    digest: fb24ed65380d9f2a71c93f29b53c1770619f65726135aec32f80e486dec150fe
    name: configuration-service
    type: application
    urls:
    - spinnaker/configuration-service-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
  currency-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-19T15:35:34.386432838Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: cf74b1ea3ee2160e8aa10a140435591628c08411752a3b8d52821be350c0923b
    name: currency-service
    type: application
    urls:
    - spinnaker/currency-service-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
  discovery-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-19T15:35:34.386904046Z"
    description: A Helm chart for Kubernetes
    digest: 34e72db7b2b9b2cef76f101d278b73473fa0b0b6967603258890c0d36dd83d7b
    name: discovery-service
    type: application
    urls:
    - spinnaker/discovery-service-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
  frontend:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-19T15:35:34.387260252Z"
    description: The frontend for car-rental application
    digest: dfbcacaf6c87fdd33ff04f0c7646bea0d309066cf594f92bb2cb7fc1dece1ab2
    name: frontend
    type: application
    urls:
    - spinnaker/frontend-0.0.1+ea86865.tgz
    version: 0.0.1+ea86865
  location-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-19T15:35:34.394020869Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: a44c3605a6f93219926873aa6d1d823853c8da0cd56b572fff54180086e0dc3f
    name: location-service
    type: application
    urls:
    - spinnaker/location-service-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
  opening-hours-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-19T15:35:34.401867605Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: 177e7ebff92bc635d31bc42c99cd9c9d7b0a130299684c0d95214bb2e411ac7a
    name: opening-hours-service
    type: application
    urls:
    - spinnaker/opening-hours-service-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
  order-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-03-19T15:35:34.408623422Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.x.x
    description: A Helm chart for Kubernetes
    digest: 0dc9cd08bf519834c72829521df10e2dc3c3f0968be712a921843ce1b417c4b3
    name: order-service
    type: application
    urls:
    - spinnaker/order-service-0.1.0+ea86865.tgz
    version: 0.1.0+ea86865
generated: "2023-03-19T15:35:34.358325951Z"
